### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [dajwill/project10#1]
I see a few issues here (testing in Chrome):

- The form labels are quite difficult to read (not enough contrast on my screen between the color of the text and the background).
- The daily commute and last visit fields don't seem to be editable in the form. I see the labels, but it looks like there's possibly a styling problem that's keeping the checkbox and select from appearing.
- There are no validations on any of the attributes, allowing me to submit a form with everything blank, which probably isn't desired. You might also want to validate that the last visit happened in the past.

Let me know if you have any questions about these.

**Comment by dajwill** [comment]
Hi Chris, I have updating some of the following on github and on the current site and now have validations. But:

-I'm still working on the last visited attribute, I may replace that with something else.
-For some reason my checkbox is not showing. I have searched everywhere to find what is causing this error and can't seemed to figure out why.

Here is my current code:
<div class="field">
    <%= f.label :daily_commute, "Daily Commute" %><br>
    <%= f.check_box :daily_commute %>
  </div>

**Comment by chrisvfritz** [comment]
Hmm, your code isn't showing up for me. You probably just need to escape it with triple ticks for the GitHub comment, [like this](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).

**Comment by chrisvfritz** [comment]
Any updates?

**Comment by chrisvfritz** [comment]
:+1:
